# Generated by Django 4.2.3 on 2023-08-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_comment_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='view_count',
        ),
        migrations.AddField(
            model_name='news',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
