# Generated by Django 4.2.3 on 2023-08-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_remove_comment_view_count_news_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
    ]
